FROM node:22-bookworm-slim

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000

COPY package*.json ./
RUN npm ci

COPY . .
ENV NODE_ENV=production
RUN npx prisma generate --schema=src/prisma/schema.prisma
RUN npm run build

EXPOSE 3000

CMD ["sh", "-c", "npm run db:migrate && npm run seed && npm run start"]
